### ISSUE TITLE
Invoice list should display the product name

### ISSUE THREAD

**Issue by eespanel** [briefmnews/briefme-invoices#1]
Not the handle or the accounting code.
![Capture d’écran 2019-11-04 à 10 12 30](https://user-images.githubusercontent.com/20476695/68144245-84ec3b80-ff33-11e9-9e74-2b44e5a9c5bb.png)

**Comment by ThomSawyer** [comment]
What's happening here has to do with Chargify.

If an "[Accounting Code](https://briefeco-sandbox.chargify.com/products)" is set in the product, Chargify sends the "Accounting Code" to us. If no "Accounting Code" is filled in it would default to the product name. In addition, it is possible for us to retrieve the product name in the statement but with the english date and the end of it i.e: "Abonnement 1 an (6 Jan 2020 - 6 Jan 2021)".

Here's what we can do:
* Remove account codes in Chargify (the fastest)
* Display the date in english (2nd fastest)
* Request the product name in Chargify

**Comment by eespanel** [comment]
I removed the accouting code because we are not using it.
